version: '3.2'
services:
    yelpcamp:
        build:
            dockerfile: Dockerfile.dev
            context: .
        volumes:
            - /app/node_modules
            - .:/app
        ports:
            - 3000:3000
    mongo:
        image: mongo:3.6.9
        command: --smallfiles
        ports:
            - 27017:27017
        volumes:
            - type: volume
              source: mongo_db
              target: /data/db
volumes:
    mongo_db:
